#!/usr/bin/env bash


L_PATH=$HOME/Projects/securityengineerd.cloud
R_PATH=/home/nextjs/securityengineerd.cloud
R_HOST=ssh.artisangift.co
R_USER=root

function writemsg {
  local INPUT_MESG=$1
  printf '%s\n' "${INPUT_MESG}"
}

printf '%s\n' "Copying current portfolio data to host."
rsync -avzP ./* root@ssh.artisangift.co:/home/nextjs/securityengineerd.cloud/ && \
    writemsg " - success" || { writemsg " - Process aborted, failed to transfer portfolio."; exit 1; }

ssh root@ssh.artisangift.co 'bash -s' < .runremote

