#!/usr/bin/env bash


L_PATH=$HOME/Projects/securityengineerd.cloud
R_PATH=/home/nextjs/securityengineerd.cloud
R_HOST=ssh.artisangift.co
R_USER=root



printf '%s\n' "Executing remote actions script."

ssh root@ssh.artisangift.co 'bash -s' < .runremote
